librato/statsd-librato-backend

README.md, lib/librato.js
Add a global prefix to namespace metrics sent to Librato which are coming from different services.
```js
{ librato: {
email: "me@example.com",
token: "abcdefghijklmnopqrstuvwxyz1234567890",
globalPrefix: "stats"
}
}
```
If set, a dot will automatically be added as separator between prefix and measurement name.
=> Added globalPrefix configuration option.

README.md
Avoid confusion that might be caused by showing a partial config file by showing a full config file.
=> Show full config file in README

README.md, lib/librato.js
Used the module **https-proxy-agent** instead of tunnel seeing that with node 0.12.7 is not working. 
Tested on our environment and it is working. Keeping on mind that I am not a node expert :D
=> Use https-proxy-agent instead of tunnel. Fixes #53

lib/librato.js
This would allow me to decide if I want the global prefix in my source or my metric name. Before the only option is to prefix the metric name.
Side note: might be nice to trim leading and trailing periods from both.
=> Add globalPrefix before performing sourceRegex match

lib/librato.js
Currently, it is assumed that the only reason a 4xx response could be returned is for 400 errors. However if a service is rate limited this result in a crash.
This should fix that.
=> Better checking for response content.

.gitignore, README.md, lib/librato.js, package.json, test/librato_tests.js
This PR adds support for measurements with tags in Librato. By default, measurements will be submitted to Librato's new API that supports tagging. We are also two config options:
- `tags` is a config option that lets you specify global tags for all measurements submitted to Librato. The `sourceName` regex will continue to function but will now be submitted for all measurements as a global tag named `source`. By default, this value is `{}`.
- `writeToLegacy` is a config option that will let you write to the legacy Librato API endpoint. This is designed to help users transition to Librato's new API and can be switched off once they are ready. By default, this value is `true`.
Librato will be adding official statsd clients, over time, to support tagging. However, it is possible to submit a …
=> Support for tagged measurements

README.md, bin/statsd-librato, package.json
- creates a `config.js` if non exists
- uses env variables to provide email, token and source
I am dockerizing our StatsD+Librato setup and felt like a `CMD` that uses environment variables to create a config file, etc. would a good idea. Do you have any interest in this?
=> Enhancement: bootstrap config and start statsd

lib/librato.js
This allows to disable sending a host tag by setting the host to `false`.
This helps in cases where statsd is not running on the same instance the tracked application is running.
=> Allow to disable hostname

lib/librato.js
Follow up from https://github.com/librato/statsd-librato-backend/pull/65.
Looks like we had some bad copy-paste around the `writeToLegacy` config value.
=> Fix bad copy-paste for writeToLegacy check

lib/librato.js
If the API responds with an HTTP 400 because the measure time is too far in the past it crashes the entire statsd server.
```
3 Mar 21:45:46 - LOG_ERR: Failed to post to Librato: HTTP 400: {"errors":{"params":{"measure_time":["is too far in the past"]}},"request_time":1488585496}
/statsd/node_modules/statsd-librato-backend/lib/librato.js:95
if (meta.errors && meta.errors.params && meta.errors.params.type.length) {
^
TypeError: Cannot read property 'length' of undefined
at IncomingMessage.<anonymous> (/statsd/node_modules/statsd-librato-backend/lib/librato.js:95:75)
at emitOne (events.js:96:13)
at IncomingMessage.emit (events.js:188:7)
at IncomingMessage.Readable.read (_stream_readable.js:381:10)
at flow (_stream_readable.js:761:34)
at resume_ (_stream_readable.js:743:3)
at …
```
=> Avoid crash when measure time is too far in the past

lib/librato.js
For legacy users on 2.0+, the payload being sent to Librato includes a `tags` attribute, an incorrect length for the `Content-Length` header and, in some cases, it would be missing a`source` attribute. This would result in invalid legacy payloads.
Example of proper payload (second one being a legacy payload):
```
13 Mar 14:55:48 - DEBUG: Sending Payload: {"time":1489434940,"tags":{"os":"el capitan","host":"Bryans-Work-MacBook-Pro.local"},"measurements":[{"name":"bryan","value":0,"tags":{"source":"digital-ocean-nyc-3"}}]}
13 Mar 14:55:48 - DEBUG: Sending Payload: {"gauges":[{"name":"bryan","value":0,"source":"digital-ocean-nyc-3"}],"counters":[],"measure_time":1489434940}
```
=> Fix invalid legacy payloads

.travis.yml
Librato, internally, uses CircleCI for all our repos. This removes TravisCI builds from this repo.
=> Move to CircleCI

.travis.yml, README.md
We need to do a better job testing this library against the major versions of Node. CircleCI is limited on their build functionality, so back to Travis we go, essentially reverting https://github.com/librato/statsd-librato-backend/pull/74
The versions of node we are going to build against:
- Everything post io.js merge
- Last major build before io.js merge
=> Bring travis back. Update build matrix

.eslintrc.json, lib/librato.js, package.json, test/librato_tests.js, yarn.lock
This PR adds eslint support. The following major changes have been made:
Unfortunately there is a bit of churn with `librato.js` due to the numerous lint failers (300+ iirc)
=> Add eslint support

lib/librato.js, test/librato_tests.js
Looks like my linter broke the method name but, even before linting, this wasn't happening due to a lack of a `.length` call.
=> Fix issue when data > maxBatchSize wouldn't send

.travis.yml, package.json, test/librato_tests.js, yarn.lock
This PR is providing some updates to our test suite. Big changes:
Hopefully, over time, we can make our test suite stronger and prevent small bugs from slipping through the cracks (such as https://github.com/librato/statsd-librato-backend/pull/79)
=> Port tests to ES6. Use nock and sinon for better mocking / stubbing

test/librato_tests.js
This was already working but we had no test coverage around it. Inspired by https://github.com/librato/statsd-librato-backend/pull/81
=> Add test for timer percentiles

lib/librato.js
This was resulting in ever increasing batches being sent and not resetting the batch when the max batch size is reached.
=> Actually flush measurements batch when batch size is reached.

test/librato_tests.js
If you revert https://github.com/librato/statsd-librato-backend/pull/93, this test will fail
=> Add a test for maxBatchSize

bin/statsd-librato
`LIBRATRO_SOURCE` should be `LIBRATO_SOURCE` in the generated `config.js` file.
=> Fix typo in generated config.js

lib/librato.js
Because some other errors might happen than the one handled (stoplist). Example, if the tag values have an invalid format, the response is something like:
```
{"measurements":{"summary":{"total":174,"accepted":78,"failed":96,"filtered":0}},"errors":[{"param":"tag_value","value":"41454@127_0_0_1","reason":"Invalid format"}]}
```
So it would be nice to log the whole response in debug mode to avoid discarding important failures.
=> Logging whole response in debug mode
